title: "Technology, Trust, and Talent: Advancing Digital Transformation Across APEC"

description: >
  An APEC workshop series exploring emerging technologies, digital trust,
  and workforce skills to advance secure and inclusive digital transformation
  across APEC economies.

baseurl: "/singapore-digital-cluster"
url: "https://usapecrise.github.io"

markdown: kramdown

logo: "/css/2016_style/img/icon-large.png"

social: []

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty
